[colors]
transparent_background_colors = true

[colors.bright]
black = "#a1a0ad"
blue = "#a4abec"
cyan = "#91e6ec"
green = "#b5e39d"
magenta = "#da8df4"
red = "#e488a6"
white = "#e1dde5"
yellow = "#e3dc81"

[colors.cursor]
cursor = "#76FF03"
text = "#000000"

[colors.dim]
black = "#404040"
blue = "#646bad"
cyan = "#51a6ad"
green = "#75a45d"
magenta = "#9b4db4"
red = "#a44866"
white = "#a19da5"
yellow = "#a39c41"

[colors.normal]
black = "#000000"
blue = "#858fe6"
cyan = "#6cdde6"
green = "#9cda7c"
magenta = "#ce67f0"
red = "#db6088"
white = "#d7d1dc"
yellow = "#d9d057"

[colors.primary]
background = "#242629"
foreground = "#d7d1dc"

[env]
TERM = "alacritty"

[font]
size = 14.5

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "ExtraLight Italic"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Semicolon"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"
