[colors]
transparent_background_colors = true

[colors.bright]
black = "#6D7070"
blue = "#54bcfb"
cyan = "#59e6f3"
green = "#b5e39d"
magenta = "#da8df4"
red = "#e47398"
white = "#FEFEF8"
yellow = "#f2df67"

[colors.cursor]
cursor = "#76FF03"
text = "#000000"

[colors.dim]
black = "#232323"
blue = "#147dbc"
cyan = "#19a7b3"
green = "#75a45d"
magenta = "#9b4db4"
red = "#a43359"
white = "#828282"
yellow = "#b29f27"

[colors.normal]
black = "#0d0d0d"
blue = "#1BA6FA"
cyan = "#21DEEF"
green = "#9cda7c"
magenta = "#ce67f0"
red = "#db4476"
white = "#EBEBEB"
yellow = "#edd434"

[colors.primary]
background = "#242629"
foreground = "#d7d1dc"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Semicolon"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"
